@startuml kml_generator

title Structure UML

package "main" {
    class MBTilesViewer {
        -root: Tk
        -mbtiles_manager: MbtilesManager        -
        -points_frame.type_creation_frame
        -points_frame.input_frame
        -points_frame.treeview_frame

              
        +setup_menu():void
        +setup_ui(self):void           
    }

    class main <<Module>>{
        +main():void
        +choisir_carte():void
    }

    main --> MBTilesViewer : Instancie
}


package "mbtiles_manager" {
    class MbtilesManager {
        +__init__(viewer):void
    }
}

package "database" {
    class Database <<Module>>{
        +create_database():void
        +database_closing(self):void
    }
}



@enduml